name: chatgpt_news_brief
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.8.4
  dio: ^5.0.0
  intl: ^0.18.0
  flutter_animate: ^4.1.1+1
  lottie: ^2.2.0
  url_launcher: ^6.1.14


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/
